apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: game
  name: agones-management-bind
subjects:
  - kind: ServiceAccount
    name: matchmaker-service-account
    namespace: game
roleRef:
  kind: Role
  name: agones-management-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: game
  name: agones-sdk-bind
subjects:
  - kind: ServiceAccount
    name: agones-sdk
    namespace: game
roleRef:
  kind: ClusterRole
  name: agones-sdk
  apiGroup: rbac.authorization.k8s.io
