apiVersion: agones.dev/v1
kind: Fleet
metadata:
  name: game-server-fleet
  namespace: game
spec:
  replicas: 1
  template:
    spec:
      health:
        disabled: true
      ports:
        - name: game
          containerPort: 5555
          portPolicy: Dynamic
          protocol: TCP
        - name: agones-sdk
          containerPort: 9357
          protocol: TCP
      template:
        spec:
          containers:
            - name: game-server
              image: test-rpg-gameserver:local
              resources:
                limits:
                  cpu: "4"
                  memory: "1Gi"