apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: game
  name: agones-management-role
rules:
  - apiGroups: [ "allocation.agones.dev" ]
    resources: [ "gameserverallocations" ]
    verbs: [ "create" ]
  - apiGroups: [ "agones.dev" ]
    resources: [ "gameservers" ]
    verbs: [get, watch, list]
    