agones:
  controller:
    persistentLogsSizeLimitMB: 500
    resources:
      requests:
        cpu: 100m
        memory: 64Mi
        ephemeral-storage: 1Gi
      limits:
        cpu: 500m
        memory: 256Mi
        ephemeral-storage: 2Gi
  
  allocator:
    resources:
      requests:
        cpu: 100m
        memory: 64Mi
        ephemeral-storage: 1Gi
      limits:
        cpu: 500m
        memory: 256Mi
        ephemeral-storage: 2Gi

  extensions:
    persistentLogsSizeLimitMB: 500
    requests:
      cpu: 100m
      memory: 64Mi
      ephemeral-storage: 500Mi
    limits:
      cpu: 500m
      memory: 256Mi
      ephemeral-storage: 1Gi

  ping:
    resources:
      requests:
        cpu: 50m
        memory: 32Mi
        ephemeral-storage: 500Mi
      limits:
        cpu: 100m
        memory: 64Mi
        ephemeral-storage: 1Gi

etcd:
  persistence:
    enabled: true
    size: 5Gi