apiVersion: "autoscaling.agones.dev/v1"
kind: FleetAutoscaler
metadata:
  name: game-autoscaler
  namespace: game
spec:
  fleetName: game-server-fleet
  policy:
    type: Buffer
    buffer:
      bufferSize: 2
      maxReplicas: 20
      minReplicas: 3
  sync:
    fixedInterval:
      seconds: 15