apiVersion: v1
kind: Secret
metadata:
  name: postgres-basic-auth
type: kubernetes.io/basic-auth
stringData:
  username: 'patryk'
  password: 'sql'

#WARNING: You should not place the username and password in the version control repository or anywhere else in plain text.
#Instead, use the Services Tool Window -> Kubernetes -> <Desired Cluster> -> Configuration -> <right-click on Secrets> -> Create New Secret...
