apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  labels:
    app: game
spec:
  serviceName: postgres-service
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:15
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: users
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-basic-auth
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-basic-auth
                  key: password
          volumeMounts:
            - name: persistentTestPostgres
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: persistentTestPostgres
      spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: "ssd"
        resources:
          requests:
            storage: 100M
      