apiVersion: v1
kind: Service
metadata:
  name: server-service
  namespace: game
spec:
  selector:
    app: server-pod
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
  